variable "aws_region" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "default_vpc_name" {}
variable "default_vpc_cidr" {}
variable "default_public_a" {}
variable "default_public_c" {}
variable "default_private_a" {}
variable "default_private_c" {}
variable "default_gw_name" {}
variable "default_iam_name" {}
variable "default_elb_name" {}
variable "default_elb_sg_name" {}
variable "default_ec2_sg_name" {}
variable "default_rds_sg_name" {}
variable "default_rds_group_name" {}
variable "default_certificate_arn" {}
variable "default_db_username" {}
variable "default_db_password" {}
variable "default_redis_sg_name" {}
variable "default_redis_group_name" {}
